// PRODUCTS METHODS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ORDER_PRODUCTS_BY_PRICE = 'ORDER_PRODUCTS_BY_PRICE'

// CART METHODS
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

//LOGIN METHODS
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const USER_LOGOUT = 'USER_LOGOUT'

export const IS_AUTH = 'IS_AUTH'